/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bb75aab1dcc586d30bf68c26f80493e3)
interface __BaseEnv_Env {
	CHAT_RATE_LIMITER: RateLimit;
	EMBEDDINGS_RATE_LIMITER: RateLimit;
	REALTIME_RATE_LIMITER: RateLimit;
	OPENAI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY">> {}
}
